# PS - Based on official yml file and then changing some defaults
# Migrated from yaml to toml using - `alacritty migrate`
[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

# PS - Color theme is Hyper - source code here - 
# https://github.com/alacritty/alacritty-theme/blob/master/themes/hyper.toml

# Default colors
[colors.primary]
background = '#000000'
foreground = '#ffffff'

[colors.cursor]
text = '#F81CE5'
cursor = '#ffffff'

# Normal colors
[colors.normal]
black = '#000000'
red = '#fe0100'
green = '#33ff00'
yellow = '#feff00'
blue = '#0066ff'
magenta = '#cc00ff'
cyan = '#00ffff'
white = '#d0d0d0'

# Bright colors
[colors.bright]
black = '#808080'
red = '#fe0100'
green = '#33ff00'
yellow = '#feff00'
blue = '#0066ff'
magenta = '#cc00ff'
cyan = '#00ffff'
white = '#FFFFFF'

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 16.0

# Font is IosevkaTerm installed as `brew install --cask font-iosevka-term-nerd-font`
[font.bold]
family = "IosevkaTerm Nerd Font"
style = "Bold"

[font.bold_italic]
family = "IosevkaTerm Nerd Font"
style = "Bold Italic"

[font.italic]
family = "IosevkaTerm Nerd Font"
style = "Italic"

[font.normal]
# family = "IosevkaTerm Nerd Font"
# I also like following sometimes, that just reduces the size of nvim tree icons
family = "IosevkaTerm Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 8

[scrolling]
history = 2000
multiplier = 4

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "transparent"
opacity = 1.0
startup_mode = "windowed"
title = "OneHotCode"

[window.padding]
x = 10
y = 30
